#pragma once

#include <FsHelpers.h>
#include <HalStorage.h>

#include <string>
#include <vector>

// Shared helpers for the MTG token viewer feature. Token images live flat in
// /tokens on the SD card as pre-dithered 1-bit BMPs (or PNGs), generated by
// tools/fetch_mtg_tokens.py.
namespace TokenScan {

constexpr char TOKENS_DIR[] = "/tokens";

// Bucket letter for a token file name: A-Z, or '#' for anything else.
inline char letterFor(const std::string& name) {
  if (name.empty()) return '#';
  const char c = name[0];
  if (c >= 'a' && c <= 'z') return static_cast<char>(c - ('a' - 'A'));
  if (c >= 'A' && c <= 'Z') return c;
  return '#';
}

// All viewable token image files in /tokens, sorted alphabetically.
inline std::vector<std::string> listTokenFiles() {
  std::vector<std::string> files;
  auto dir = Storage.open(TOKENS_DIR);
  if (!dir || !dir.isDirectory()) {
    if (dir) dir.close();
    return files;
  }
  char name[500];
  for (auto file = dir.openNextFile(); file; file = dir.openNextFile()) {
    if (!file.isDirectory()) {
      file.getName(name, sizeof(name));
      if (name[0] != '.') {
        std::string fname(name);
        if (FsHelpers::hasBmpExtension(fname) || FsHelpers::hasPngExtension(fname)) {
          files.push_back(fname);
        }
      }
    }
    file.close();
  }
  dir.close();
  FsHelpers::sortFileList(files);
  return files;
}

// Strip the file extension for display.
inline std::string displayName(const std::string& fileName) {
  const size_t dot = fileName.find_last_of('.');
  return dot == std::string::npos ? fileName : fileName.substr(0, dot);
}

}  // namespace TokenScan
